#!/bin/bash
# symlinkFastqs

Help()
{
    progname=`basename $0`
    # Display Help
    echo "Make symlinks for gzipped FastQ files in current directory to input directory."
    echo
    echo "Syntax: $progname [-i|d|f|p|r|h]"
    echo "options:"
    echo -e "\t-i    required; input directory with gzipped fastqs"
    echo -e "\t-d    required; delimiter for finding sample names (see cut)"
    echo -e "\t-f    required; number of field in which to find sample names (see cut)"
    echo -e "\t-m    matching pattern for files you want to link. Default is 'lane*fastq.gz'. Must be in quotes"
    echo -e "\t-s    character(s) to split the sample name from the read ID in link name\n\t\te.g. sample01-R1.fastq.gz OR sample01--R1.fastq.gz\n\t\tdefault is '-'"
    echo -e "\t-p    pattern in sample names to be replaced\n\t\t(can be used multiple times, order matters)"
    echo -e "\t-r    string to replace patterns\n\t\t(can be used multiple times, order matters)"
    echo -e "\t-h    this help screen"
    echo
}

SPLIT='-'
MATCH="lane*fastq.gz"
while getopts i:d:f:m:p:r:h flag; do
    case "${flag}" in
        i) INDIR=${OPTARG};;
        d) DELIM=${OPTARG};;
        f) FIELD=${OPTARG};;
        m) MATCH=${OPTARG};;
        s) SPLIT=${OPTARG};;
        p) PATTERNS+=("$OPTARG");;
        r) REPLACES+=("$OPTARG");;
        h) Help; exit;;
    esac
done

for FASTQ in ${INDIR}/${MATCH}; do
    NAME=`basename $FASTQ | cut -d $DELIM -f $FIELD`
    if [ ${#PATTERNS[@]} -gt 0 ]; then
        for I in "${!PATTERNS[@]}"; do
            NAME=`echo $NAME | sed "s/${PATTERNS[$I]}/${REPLACES[$I]}/g"`
        done
    fi
    READ=`echo $FASTQ | grep -o "R[12]"`
    ln -sv $FASTQ ${NAME}${SPLIT}${READ}.fastq.gz
done

