#!/bin/bash
# generate_kneaddata_array_commands.sh

Help()
{
    progname=`basename $0`
    # Display Help
    echo "Create a text file of commands to be passed to SGE_array and print command for user to copy and run."
    echo
    echo "Syntax: $progname [-i|d|o|q|t|p|c|m|s|f|b|z|h]"
    echo "options:"
    echo -e "\t-i    required; input directory with gzipped fastqs (or symlinks to them)"
    echo -e "\t-d    required; location of genome database for knead"
    echo -e "\t-o    required; final output directory"
    echo -e "\t-q    required; the queue the array commands will be sent to"
    echo -e "\t-t    temporary output directory for initial results\n\t\tfiles will then be moved to final output directory\n\t\t(gzipped prior to moving if -z is enabled)"
    echo -e "\t-p    number of processors for each command to use in array, default is 1"
    echo -e "\t-c    number of concurrent jobs to run in array, default is 1"
    echo -e "\t-m    amount of memory to allocate to array, default is 10G"
    echo -e "\t-s    character(s) to split the sample name from the read ID in link name\n\t\te.g. sample01-R1.fastq.gz OR sample01--R1.fastq.gz\n\t\tdefault is '-'"
    echo -e "\t-f    file to write commands to, default is 'kneaddata_array_commands.txt'"
    echo -e "\t-b    addtional qsub options, need to be in quotes"
    echo -e "\t-z    gzip results"
    echo -e "\t-h    this help screen"
    echo
}

PROC=1
CONC=1
MEM=10G
SPLIT='-'
CMDFILE=kneaddata_array_commands.txt
GZIP=0
while getopts i:d:o:q:t:p:c:m:s:f:b:zh flag; do
    case "${flag}" in
        i) INDIR=${OPTARG};;
        d) DB=${OPTARG};;
        o) OUTDIR=${OPTARG};;
        q) QUEUE=${OPTARG};;
        t) TMPDIR=${OPTARG};;
        p) PROC=${OPTARG};;
        c) CONC=${OPTARG};;
        m) MEM=${OPTARG};;
        s) SPLIT=${OPTARG};;
        f) CMDFILE=${OPTARG};;
        b) QSUB_OPTS=${OPTARG};;
        z) GZIP=1;;
        h) Help; exit;;
    esac
done

if [[ -f $CMDFILE ]]; then
    rm $CMDFILE
fi

if [ $TMPDIR ]; then
    DIRECTOUT=$TMPDIR
elif [ $OUTDIR ]; then
    DIRECTOUT=$OUTDIR
else
    Help
    exit 1
fi

for FASTQ in ${INDIR}/*R1*fastq.gz; do
    NAME=`basename $FASTQ | cut -d $SPLIT -f 1`
    INPUT1=$FASTQ
    INPUT2=${INDIR}/${NAME}-R2.fastq.gz
    echo -n \
        "kneaddata" \
            "-t $PROC" \
            "--input $INPUT1" \
            "--input $INPUT2" \
            "--reference-db $DB" \
            "--output $DIRECTOUT ; " \
    >> $CMDFILE
    if [ $GZIP ]; then
         echo -n "gzip -v ${DIRECTOUT}/*${NAME}* ; " >> $CMDFILE
    fi
    if [ $TMPDIR ]; then
        echo -n "mv -v ${DIRECTOUT}/*${NAME}* $OUTDIR ; " >> $CMDFILE
    fi
    echo >> $CMDFILE
done

echo "Please run the following command:"
echo -ne \
    "\tSGE_Array" \
        "-c $CMDFILE" \
        "-q $QUEUE" \
        "-P $PROC" \
        "-f $MEM"
if [ $CONC ]; then
    echo -n " -b $CONC"
fi
if [ ${#QSUB_OPTS[@]} ]; then
    echo " --qsub_options='${QSUB_OPTS[@]}'"
else
    echo
fi