#!/bin/bash
# generate_humann3_array_commands.sh

Help()
{
    progname=`basename $0`
    # Display Help
    echo "Create a text file of commands to be passed to SGE_array and print command for user to copy and run."
    echo
    echo "Syntax: $progname [-i|d|o|q|t|p|c|m|s|f|z|h]"
    echo "options:"
    echo -e "\t-i    required; input directory with gzipped fastqs (or symlinks to them)"
    echo -e "\t-o    required; final output directory"
    echo -e "\t-q    required; the queue the array commands will be sent to"
    echo -e "\t-t    temporary output directory for initial results\n\t\tfiles will then be moved to final output directory\n\t\t(gzipped prior to moving if -z is enabled)"
    echo -e "\t-p    number of processors for each command to use in array, default is 1"
    echo -e "\t-c    number of concurrent jobs to run in array, 0 will leave it unspecified, letting the SGE scheduler figure it out; default is 0"
    echo -e "\t-m    amount of memory to allocate to array, default is 10G"
    echo -e "\t-s    character(s) to split the sample name from the read ID in link name\n\t\te.g. sample01-R1.fastq.gz OR sample01--R1.fastq.gz\n\t\tdefault is '-'"
    echo -e "\t-f    file to write commands to, default is 'humann3_array_commands.txt'"
    echo -e "\t-b    addtional qsub options, need to be in quotes"
    echo -e "\t-z    gzip results"
    echo -e "\t-h    this help screen"
    echo
}

PROC=1
CONC=0
MEM=10G
SPLIT='-'
CMDFILE=humann3_array_commands.txt
GZIP=0
while getopts i:d:o:q:t:p:c:m:s:f:b:zh flag; do
    case "${flag}" in
        i) INDIR=${OPTARG};;
        o) OUTDIR=${OPTARG};;
        q) QUEUE=${OPTARG};;
        t) TMPDIR=${OPTARG};;
        p) PROC=${OPTARG};;
        c) CONC=${OPTARG};;
        m) MEM=${OPTARG};;
        f) CMDFILE=${OPTARG};;
        b) QSUB_OPTS=${OPTARG};;
        z) GZIP=1;;
        h) Help; exit;;
    esac
done

if [[ -f $CMDFILE ]]; then
    rm $CMDFILE
fi

if [ $TMPDIR ]; then
    DIRECTOUT=$TMPDIR
elif [ $OUTDIR ]; then
    DIRECTOUT=$OUTDIR
else
    Help
    exit 1
fi

for FASTQ in ${INDIR}/*; do
    NAME=`basename $FASTQ | cut -f 1 -d '.'`
    echo -n \
        "humann --input $FASTQ --output $DIRECTOUT --threads $PROC ; " \
    >> $CMDFILE
    if [ $GZIP ]; then
        echo -n \
            "tar zvcf" \
                "${DIRECTOUT}/${NAME}_humann_temp.tgz" \
                "${DIRECTOUT}/${NAME}_humann_temp ;" \
            "gzip ${DIRECTOUT}/${NAME}*tsv ; " \
        >> $CMDFILE
    fi
    if [ $TMPDIR ]; then
        echo -n \
            "mv -v ${TMPDIR}/${NAME}_humann_temp.tgz $OUTDIR ; " \
            "mv -v ${TMPDIR}/${NAME}*tsv.gz $OUTDIR ; " \
        >> $CMDFILE
    fi
    echo >> $CMDFILE
done

echo "Please run the following command:"
echo -ne \
    "\tSGE_Array" \
        "-c $CMDFILE" \
        "-q $QUEUE" \
        "-P $PROC" \
        "-f $MEM"
if [ $CONC ]; then
    echo -n " -b $CONC"
fi
if [ ${#QSUB_OPTS[@]} -gt 0 ]; then
    echo " --qsub_options='${QSUB_OPTS[@]}'"
else
    echo
fi
